/**
 * Coin search index — loads coin-search-index.json once and provides
 * fast prefix-based filtering against canonical IDs, symbols, names,
 * and all aliases.
 *
 * The index is generated by:  node frontend/scripts/build-search-index.mjs
 * and served as a static file from /coin-search-index.json.
 */

let _cache = null

/**
 * Load the search index (fetched once, cached in memory).
 * @returns {Promise<Array<{id:string, symbol:string, name:string, aliases:string[]}>>}
 */
export async function loadSearchIndex() {
    if (_cache) return _cache

    try {
        const res = await fetch("/coin-search-index.json")
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        _cache = await res.json()
        return _cache
    } catch (err) {
        console.error("[CoinSearch] Failed to load search index:", err)
        return []
    }
}

/**
 * Search the index. Returns coins where ANY of the following starts
 * with the query (case-insensitive):
 *   - canonical id  ("bitcoin")
 *   - symbol        ("btc")
 *   - display name  ("Bitcoin")
 *   - any alias     ("xbt")
 *
 * This means typing "a" returns ADA, AVAX, etc.
 * Typing "xb" returns Bitcoin (alias "xbt") and nothing else.
 *
 * @param {string} query  User's input string
 * @param {Array}  index  Pre-loaded index (from loadSearchIndex)
 * @returns {Array}  Matching coin objects, sorted by best match
 */
export function searchCoins(query, index) {
    if (!query || !index) return []

    const q = query.trim().toLowerCase()
    if (!q) return []

    // Score each coin by match quality so we can sort results
    const scored = []

    for (const coin of index) {
        let bestScore = 0

        // Exact match on id or symbol → highest score
        if (coin.id === q || coin.symbol.toLowerCase() === q) {
            bestScore = 100
        }
        // id or symbol starts with query → high score
        else if (coin.id.startsWith(q) || coin.symbol.toLowerCase().startsWith(q)) {
            bestScore = 80
        }
        // display name starts with query
        else if (coin.name.toLowerCase().startsWith(q)) {
            bestScore = 70
        }
        // any alias starts with query
        else {
            for (const alias of coin.aliases) {
                if (alias.startsWith(q)) {
                    bestScore = 60
                    break
                }
            }
        }

        // Contains anywhere (weaker match, but still returned)
        if (!bestScore) {
            if (
                coin.id.includes(q) ||
                coin.symbol.toLowerCase().includes(q) ||
                coin.name.toLowerCase().includes(q) ||
                coin.aliases.some((a) => a.includes(q))
            ) {
                bestScore = 30
            }
        }

        if (bestScore > 0) {
            scored.push({ coin, score: bestScore })
        }
    }

    // Sort: highest score first, then alphabetically
    scored.sort((a, b) => b.score - a.score || a.coin.name.localeCompare(b.coin.name))

    return scored.map((s) => s.coin)
}
